"""
Python bindings for the Metal Procedural Art Engine
"""
from __future__ import annotations
import collections.abc
import glm
import typing
__all__: list[str] = ['Canvas', 'Circle', 'Image', 'Layer', 'Primitive', 'Square', 'close', 'display', 'engine', 'poll_events', 'render']
class Canvas:
    def __init__(self, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def addLayer(self, arg0: Layer) -> None:
        ...
    def height(self) -> int:
        ...
    def newLayer(self) -> Layer:
        ...
    def render(self) -> None:
        ...
    def renderOut(self, path: str) -> None:
        ...
    def width(self) -> int:
        ...
class Circle(Primitive):
    color: glm.vec4
    size: glm.vec2
    def __init__(self, width: typing.SupportsFloat | typing.SupportsIndex, height: typing.SupportsFloat | typing.SupportsIndex, r: typing.SupportsFloat | typing.SupportsIndex, g: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, a: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Image(Primitive):
    def __init__(self, arg0: str) -> None:
        ...
    def setSize(self, arg0: glm.vec2) -> None:
        ...
class Layer:
    def __init__(self) -> None:
        ...
    def draw(self, primitive: Primitive, matrix: glm.mat4x4 = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]) -> None:
        ...
class Primitive:
    def render(self, arg0: ..., arg1: glm.mat4x4, arg2: glm.vec2, arg3: glm.vec2) -> None:
        ...
class Square(Primitive):
    color: glm.vec4
    size: glm.vec2
    def __init__(self, width: typing.SupportsFloat | typing.SupportsIndex, height: typing.SupportsFloat | typing.SupportsIndex, r: typing.SupportsFloat | typing.SupportsIndex, g: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex, a: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
def close() -> None:
    ...
def display(arg0: Canvas) -> None:
    ...
def engine() -> Engine:
    ...
def poll_events() -> None:
    ...
def render(arg0: collections.abc.Callable) -> None:
    ...
