"""
Python bindings for the Metal Procedural Art Engine
"""
from __future__ import annotations
import collections.abc
import glm
import typing
__all__: list[str] = ['Canvas', 'Circle', 'Image', 'Layer', 'Primitive', 'Square', 'TintFunction', 'close', 'display', 'endCommandBuffer', 'engine', 'poll_events', 'render', 'startCommandBuffer', 'tint']
class Canvas:
    def __init__(self, width: typing.SupportsInt | typing.SupportsIndex, height: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def add_layer(self, layer: Layer) -> None:
        ...
    def height(self) -> int:
        ...
    def new_layer(self) -> Layer:
        ...
    def render(self) -> None:
        ...
    def render_out(self, path: str) -> None:
        ...
    def width(self) -> int:
        ...
class Circle(Primitive):
    color: glm.vec4
    size: glm.vec2
    def __init__(self, size: glm.vec2, color: glm.vec4) -> None:
        ...
class Image(Primitive):
    size: glm.vec2
    @typing.overload
    def __init__(self, image_path: str) -> None:
        ...
    @typing.overload
    def __init__(self, image_path: str, size: glm.vec2) -> None:
        ...
    def set_size(self, size: glm.vec2) -> None:
        ...
class Layer:
    def __init__(self) -> None:
        ...
    @typing.overload
    def draw(self, primitive: Primitive) -> None:
        ...
    @typing.overload
    def draw(self, primitive: Primitive, transform_px: glm.mat4x4) -> None:
        ...
    @typing.overload
    def draw(self, primitive: Primitive, transform_px: glm.mat4x4, size_px: glm.vec2) -> None:
        ...
class Primitive:
    def __init__(self) -> None:
        ...
class Square(Primitive):
    color: glm.vec4
    size: glm.vec2
    def __init__(self, size: glm.vec2, color: glm.vec4) -> None:
        ...
class TintFunction(Primitive):
    def __init__(self) -> None:
        ...
def close() -> None:
    ...
def display(canvas: Canvas) -> None:
    ...
def endCommandBuffer() -> None:
    ...
def engine() -> Engine:
    ...
def poll_events() -> None:
    ...
def render(callback: collections.abc.Callable) -> None:
    ...
def startCommandBuffer() -> None:
    ...
def tint(arg0: Primitive, arg1: glm.vec4) -> TintFunction:
    ...
